# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 08cc5990a1928b462c77eb224c83163fee80cdaf9c406ecd4e43e3d7898e0740285333e26935079de576c2ea1e614db5a5dea314bd8478e2521dac033aeeb2f2

test:
  secret_key_base: aef301cb383200d33fcab03b85fba6bbf831d69dc687b3aaf9c0528c8d98d280caf56c8558c2eafd8f1af4566d2d6fe9516f485d528547ff05d70dccf66d2a6c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
